# Generated by Django 2.0.5 on 2018-06-06 20:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('short_des', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('create_date', models.DateTimeField(default=datetime.datetime(2018, 6, 6, 20, 30, 21, 134165, tzinfo=utc))),
            ],
        ),
    ]
