# Generated by Django 2.0.5 on 2018-06-06 20:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
